In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("../Inputs/attacks.csv", encoding="latin")
df.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [8]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,25713,25714,25715,25716,25717,25718,25719,25720,25721,25722
Case Number,2018.06.25,2018.06.18,2018.06.09,2018.06.08,2018.06.04,2018.06.03.b,2018.06.03.a,2018.05.27,2018.05.26.b,2018.05.26.a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,xx
Date,25-Jun-2018,18-Jun-2018,09-Jun-2018,08-Jun-2018,04-Jun-2018,03-Jun-2018,03-Jun-2018,27-May-2018,26-May-2018,26-May-2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Year,2018,2018,2018,2018,2018,2018,2018,2018,2018,2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Type,Boating,Unprovoked,Invalid,Unprovoked,Provoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country,USA,USA,USA,AUSTRALIA,MEXICO,AUSTRALIA,BRAZIL,USA,USA,USA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Area,California,Georgia,Hawaii,New South Wales,Colima,New South Wales,Pernambuco,Florida,Florida,Florida,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Location,"Oceanside, San Diego County","St. Simon Island, Glynn County","Habush, Oahu",Arrawarra Headland,La Ticla,"Flat Rock, Ballina","Piedade Beach, Recife","Lighhouse Point Park, Ponce Inlet, Volusia County","Cocoa Beach, Brevard County","Daytona Beach, Volusia County",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Activity,Paddling,Standing,Surfing,Surfing,Free diving,Kite surfing,Swimming,Fishing,Walking,Standing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Name,Julie Wolfe,Adyson McNeely,John Denges,male,Gustavo Ramos,Chris,Jose Ernesto da Silva,male,Cody High,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sex,F,F,M,M,M,M,M,M,M,M,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,57,11,48,NaN,NaN,NaN,18,52,15,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Injury,"No injury to occupant, outrigger canoe and pad...",Minor injury to left thigh,Injury to left lower leg from surfboard skeg,Minor injury to lower leg,Lacerations to leg & hand shark PROVOKED INCIDENT,"No injury, board bitten",FATAL,Minor injury to foot. PROVOKED INCIDENT,Lower left leg bitten,Minor injury to foot,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fatal (Y/N),N,N,N,N,N,N,Y,N,N,N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time,18h00,14h00 -15h00,07h45,NaN,NaN,NaN,Late afternoon,NaN,17h00,14h00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Species,White shark,NaN,NaN,2 m shark,"Tiger shark, 3m",NaN,Tiger shark,"Lemon shark, 3'","Bull shark, 6'",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Investigator or Source,"R. Collier, GSAF","K.McMurray, TrackingSharks.com","K.McMurray, TrackingSharks.com","B. Myatt, GSAF",A .Kipper,"Daily Telegraph, 6/4/2018","Diario de Pernambuco, 6/4/2018","K. McMurray, TrackingSharks.com","K.McMurray, TrackingSharks.com","K. McMurray, Tracking Sharks.com",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pdf,2018.06.25-Wolfe.pdf,2018.06.18-McNeely.pdf,2018.06.09-Denges.pdf,2018.06.08-Arrawarra.pdf,2018.06.04-Ramos.pdf,2018.06.03.b-FlatRock.pdf,2018.06.03.a-daSilva.pdf,2018.05.27-Ponce.pdf,2018.05.26.b-High.pdf,2018.05.26.a-DaytonaBeach.pdf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
href formula,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
href,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Case Number.1,2018.06.25,2018.06.18,2018.06.09,2018.06.08,2018.06.04,2018.06.03.b,2018.06.03.a,2018.05.27,2018.05.26.b,2018.05.26.a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Case Number.2,2018.06.25,2018.06.18,2018.06.09,2018.06.08,2018.06.04,2018.06.03.b,2018.06.03.a,2018.05.27,2018.05.26.b,2018.05.26.a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
original order,6303,6302,6301,6300,6299,6298,6297,6296,6295,6294,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.shape

(25723, 24)

In [15]:
df.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [17]:
df["Case Number"]

0        2018.06.25
1        2018.06.18
2        2018.06.09
3        2018.06.08
4        2018.06.04
            ...
25718           NaN
25719           NaN
25720           NaN
25721           NaN
25722            xx
Name: Case Number, Length: 25723, dtype: object

In [21]:
working_columns = df[['Date', 'Year','Type', 'Country', 'Area','Activity','Age', 'Injury', 'Fatal (Y/N)', 'Time','Species ']]
working_columns.head()

,Date,Year,Type,Country,Area,Activity,Age,Injury,Fatal (Y/N),Time,Species
0,25-Jun-2018,2018.0,Boating,USA,California,Paddling,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark
1,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,Standing,11,Minor injury to left thigh,N,14h00 -15h00,NaN
2,09-Jun-2018,2018.0,Invalid,USA,Hawaii,Surfing,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN
3,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Surfing,NaN,Minor injury to lower leg,N,NaN,2 m shark
4,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,Free diving,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m"